theme: minima

title: The Blog
author: Devin Cody
description: > # this means to ignore newlines until "baseurl:"
  This space will be used to discuss engineering, science, and programming. More info to come.



github_username:  devincody
linkedin_username: devincody
google_analytics: "UA-116951629-1"
